name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # Install NuGet
    - name: Setup Nuget.exe
      uses: NuGet/setup-nuget@v1.0.5

    # Install .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # Install MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # Restore projects
    - name: Restore Projects
      run: dotnet restore "src/Hostly/Hostly.csproj"
    - name: Restore Hostly.Android
      run: nuget restore "src/Hostly.Android/Hostly.Android.csproj"
    - name: Restore Hostly.iOS
      run: nuget restore "src/Hostly.iOS/Hostly.iOS.csproj"
    - name: Restore Hostly.UWP
      run: nuget restore "src/Hostly.UWP/Hostly.UWP.csproj"

    # Build projects
    - name: Build Projects
      run: dotnet build "src/Hostly/Hostly.csproj" --configuration Release --no-restore
    - name: Build Hostly.Android
      run: msbuild "src/Hostly.Android/Hostly.Android.csproj" -p:Configuration=Release
    - name: Build Hostly.iOS
      run: msbuild "src/Hostly.iOS/Hostly.iOS.csproj" -p:Configuration=Release
    - name: Build Hostly.UWP
      run: msbuild "src/Hostly.UWP/Hostly.UWP.csproj" -p:Configuration=Release

    # Test projects
    - name: Test projects
      run: dotnet test Hostly.sln --configuration Release --no-restore --no-build --verbosity normal --filter Category=Unit -- xunit.parallelizeAssembly=true