name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # Install NuGet
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    # Install .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # Install MSBuild
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1

    # Restore projects
    - name: Restore Hostly
      run: dotnet restore "src/Hostly/Hostly.csproj"
    - name: Restore Hostly.Android
      run: nuget restore "src/Hostly.Android/Hostly.Android.csproj"
    - name: Restore Hostly.iOS
      run: nuget restore "src/Hostly.iOS/Hostly.iOS.csproj"

    # Build projects
    - name: Build Hostly
      run: dotnet build "src/Hostly/Hostly.csproj" --configuration Release --no-restore
    - name: Build Hostly.Android
      run: msbuild "src/Hostly.Android/Hostly.Android.csproj" -p:Configuration=Release
    - name: Build Hostly.iOS
      run: msbuild "src/Hostly.iOS/Hostly.iOS.csproj" -p:Configuration=Release

    # Test projects
    - name: Test
      run: dotnet test "tests/Hostly.Tests/Hostly.Tests.csproj" --no-restore --verbosity normal